import 'package:flutter/material.dart';
import 'dart:io';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Profil(),
        ]),
      ),
    );
  }
}

class Profil extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF8F8F9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(50),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 302,
                child: Container(
                  height: 286,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 354,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Nama',
                                  style: TextStyle(
                                    color: Color(0xFF333333),
                                    fontSize: 12,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: 0.12,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 47,
                                child: Opacity(
                                  opacity: 0.50,
                                  child: Container(
                                    width: 354,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 0.50,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 24,
                                child: Text(
                                  'ilham islamy',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w500,
                                    height: 0.05,
                                    letterSpacing: 0.18,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 47,
                                child: Opacity(
                                  opacity: 0.50,
                                  child: Container(
                                    width: 354,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 0.50,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 78,
                        child: Container(
                          width: 354,
                          height: 50,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Email',
                                  style: TextStyle(
                                    color: Color(0xFF333333),
                                    fontSize: 12,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: 0.12,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 50,
                                child: Opacity(
                                  opacity: 0.50,
                                  child: Container(
                                    width: 354,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 0.50,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 3,
                                top: 24,
                                child: Text(
                                  'ilham1745@gmail.com',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w500,
                                    height: 0.05,
                                    letterSpacing: 0.18,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 160,
                        child: Container(
                          width: 354,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Nomor Telepon',
                                  style: TextStyle(
                                    color: Color(0xFF333333),
                                    fontSize: 12,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: 0.12,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 47,
                                child: Opacity(
                                  opacity: 0.50,
                                  child: Container(
                                    width: 354,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 0.50,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 24,
                                child: Text(
                                  '081234567890',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w500,
                                    height: 0.05,
                                    letterSpacing: 0.18,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 239,
                        child: Container(
                          width: 354,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Alamat',
                                  style: TextStyle(
                                    color: Color(0xFF333333),
                                    fontSize: 12,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: 0.12,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 47,
                                child: Opacity(
                                  opacity: 0.50,
                                  child: Container(
                                    width: 354,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 0.50,
                                          strokeAlign: BorderSide.strokeAlignCenter,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 3,
                                top: 22,
                                child: Text(
                                  'Berbek, Nganjuk',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'DM Sans',
                                    fontWeight: FontWeight.w500,
                                    height: 0.05,
                                    letterSpacing: 0.18,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 138,
                top: 126,
                child: Container(
                  width: 166.80,
                  height: 150,
                  child: Stack(children: [
                  
                  ]),
                ),
              ),
              Positioned(
                left: 38,
                top: 794,
                child: Container(
                  width: 138,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 138,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFFB700),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: Colors.white.withOpacity(0.5),
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                           shadows: [
  BoxShadow(
    color: Color(0x7F000000),
    blurRadius: 20,
    offset: Offset(10, 10),
    spreadRadius: 0,
  ),
  BoxShadow(
    color: Color(0x7FFFFFFF),
    blurRadius: 20,
    offset: Offset(-10, -10),
    spreadRadius: 0,
  )
],

                          ),
                        ),
                      ),
                      Positioned(
                        left: 36,
                        top: 12.13,
                        child: SizedBox(
                          width: 65,
                          height: 19.72,
                          child: Text(
                            'Edit',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 244,
                top: 794,
                child: Container(
                  width: 138,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 138,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: Color(0xBFFF1A00),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: Colors.white.withOpacity(0.5),
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                           shadows: [
  BoxShadow(
    color: Color(0x7F000000),
    blurRadius: 20,
    offset: Offset(10, 10),
    spreadRadius: 0,
  ),
  BoxShadow(
    color: Color(0x7FFFFFFF),
    blurRadius: 20,
    offset: Offset(-10, -10),
    spreadRadius: 0,
  ),
],

                          ),
                        ),
                      ),
                      Positioned(
                        left: 36,
                        top: 12.13,
                        child: SizedBox(
                          width: 65,
                          height: 19.72,
                          child: Text(
                            'Logout',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 172,
                top: 62,
                child: Text(
                  'Profil',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 32,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w700,
                    height: 0.02,
                    letterSpacing: 0.32,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 872,
                child: Container(
                  width: 428,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFFFF8577)),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 4,
                        child: Container(
                          width: 263,
                          height: 52,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 42,
                                  height: 52,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 3,
                                        top: 0,
                                        child: Container(
                                          width: 33,
                                          height: 31.55,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 32,
                                                  height: 31.55,
                                                  decoration: BoxDecoration(color: Colors.white),
                                                ),
                                              ),
                                              Positioned(
                                                left: 3,
                                                top: 0,
                                                child: Container(
                                                  width: 30,
                                                  height: 29.58,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                    
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 33,
                                        child: Text(
                                          'Home',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 14,
                                            fontFamily: 'Amiko',
                                            fontWeight: FontWeight.w400,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 226,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 52,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 3.17,
                                        top: 0,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 30,
                                                  height: 30,
                                                  decoration: BoxDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: -2.40,
                                                child: Container(
                                                  width: 32.40,
                                                  height: 38.40,
                                                  decoration: BoxDecoration(color: Colors.white),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 33,
                                        child: Text(
                                          'Profil',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 14,
                                            fontFamily: 'Amiko',
                                            fontWeight: FontWeight.w400,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 102,
                                top: 0,
                                child: Container(
                                  width: 64.18,
                                  height: 48.09,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 32,
                                        child: SizedBox(
                                          width: 64.18,
                                          height: 16.09,
                                          child: Text(
                                            'Riwayat',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 14,
                                              fontFamily: 'DM Sans',
                                              fontWeight: FontWeight.w700,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}