import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Riwayat(),
        ]),
      ),
    );
  }
}

class Riwayat extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF8F8F9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(50),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 149,
                top: 62,
                child: Text(
                  'Riwayat',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 32,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w700,
                    height: 0.02,
                    letterSpacing: 0.32,
                  ),
                ),
              ),
              Positioned(
                left: 31.01,
                top: 96,
                child: Container(
                  width: 365.97,
                  height: 90,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF8F8F8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 89.94,
                        top: 45,
                        child: SizedBox(
                          width: 201.59,
                          height: 30,
                          child: Text(
                            'Anda pernah melakukan Variasi pada tanggal 20-10-23',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5799999833106995),
                              fontSize: 11,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89.94,
                        top: 24,
                        child: SizedBox(
                          width: 191.26,
                          height: 21,
                          child: Text(
                            'Brio 2017 (putih)',
                            style: TextStyle(
                              color: Color(0xFF2B4C59),
                              fontSize: 14,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16.54,
                        top: 20,
                        child: Container(
                          width: 55.83,
                          height: 55,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/56x55"),
                              fit: BoxFit.contain,
                            ),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32.05,
                top: 197,
                child: Container(
                  width: 365.97,
                  height: 90,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 89.94,
                        top: 45,
                        child: SizedBox(
                          width: 201.59,
                          height: 30,
                          child: Text(
                            'Anda pernah melakukan Detailing pada tanggal 10-10-23',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5799999833106995),
                              fontSize: 11,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89.94,
                        top: 24,
                        child: SizedBox(
                          width: 187.12,
                          height: 21,
                          child: Text(
                            'Brio 2017 (putih)',
                            style: TextStyle(
                              color: Color(0xFF2B4C59),
                              fontSize: 14,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17.95,
                        top: 20,
                        child: Container(
                          width: 55.83,
                          height: 55,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/56x55"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32.05,
                top: 298,
                child: Container(
                  width: 365.97,
                  height: 90,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF8F8F8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 89.94,
                        top: 45,
                        child: SizedBox(
                          width: 201.59,
                          height: 30,
                          child: Text(
                            'Anda pernah melakukan Detailing pada tanggal 27-9-23',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5799999833106995),
                              fontSize: 11,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89.94,
                        top: 24,
                        child: SizedBox(
                          width: 173.68,
                          height: 21,
                          child: Text(
                            'Brio 2017 (putih)',
                            style: TextStyle(
                              color: Color(0xFF2B4C59),
                              fontSize: 14,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16.54,
                        top: 20,
                        child: Container(
                          width: 55.83,
                          height: 55,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/56x55"),
                              fit: BoxFit.contain,
                            ),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32.05,
                top: 399,
                child: Container(
                  width: 365.97,
                  height: 90,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF8F8F8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 89.94,
                        top: 45,
                        child: SizedBox(
                          width: 201.59,
                          height: 30,
                          child: Text(
                            'Anda pernah melakukan Variasi pada tanggal 29-9-23',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5799999833106995),
                              fontSize: 11,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89.94,
                        top: 24,
                        child: SizedBox(
                          width: 191.26,
                          height: 21,
                          child: Text(
                            'Brio 2017 (putih)',
                            style: TextStyle(
                              color: Color(0xFF2B4C59),
                              fontSize: 14,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16.54,
                        top: 20,
                        child: Container(
                          width: 55.83,
                          height: 55,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/56x55"),
                              fit: BoxFit.contain,
                            ),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 872,
                child: Container(
                  width: 428,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFFFF8577)),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 4,
                        child: Container(
                          width: 263,
                          height: 52,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 42,
                                  height: 52,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 3,
                                        top: 0,
                                        child: Container(
                                          width: 33,
                                          height: 31.55,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 32,
                                                  height: 31.55,
                                                  decoration: BoxDecoration(color: Colors.white),
                                                ),
                                              ),
                                              Positioned(
                                                left: 3,
                                                top: 0,
                                                child: Container(
                                                  width: 30,
                                                  height: 29.58,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                    
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 33,
                                        child: Text(
                                          'Home',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 14,
                                            fontFamily: 'Amiko',
                                            fontWeight: FontWeight.w400,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 226,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 52,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 3.17,
                                        top: 0,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 30,
                                                  height: 30,
                                                  decoration: BoxDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: -2.40,
                                                child: Container(
                                                  width: 32.40,
                                                  height: 38.40,
                                                  decoration: BoxDecoration(color: Colors.white),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 33,
                                        child: Text(
                                          'Profil',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 14,
                                            fontFamily: 'Amiko',
                                            fontWeight: FontWeight.w400,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 102,
                                top: 0,
                                child: Container(
                                  width: 64.18,
                                  height: 48.09,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 32,
                                        child: SizedBox(
                                          width: 64.18,
                                          height: 16.09,
                                          child: Text(
                                            'Riwayat',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 14,
                                              fontFamily: 'DM Sans',
                                              fontWeight: FontWeight.w700,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}